services:
  db:
    image: postgres:16-alpine
    container_name: crm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: crm_admin
      POSTGRES_PASSWORD: crm_secure_password
      POSTGRES_DB: crm_main_database
    volumes:
      - crm_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./services/core
    container_name: crm_backend_core
    restart: always
    volumes:
      - ./services/core:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://crm_admin:crm_secure_password@db:5432/crm_main_database
    depends_on:
      - db

  logger:
    build: ./services/logger
    container_name: crm_logger_service
    restart: always
    volumes:
      - ./services/logger:/app
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  frontend:
    build: ./frontend
    container_name: crm_frontend_react
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Защищает локальную папку от перезаписи
    ports:
      - "5173:5173"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

volumes:
  crm_pg_data:
