version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: crm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: crm_admin
      POSTGRES_PASSWORD: crm_secure_password
      POSTGRES_DB: crm_main_database
    volumes:
      - crm_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  crm_pg_data:
