"""feat: add purchase_rules table model

Revision ID: 09cf7df8a4fe
Revises: 7bc25ab76b3a
Create Date: 2026-06-17 11:45:17.172589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cf7df8a4fe'
down_revision: Union[str, Sequence[str], None] = '7bc25ab76b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_operator', sa.String(length=50), nullable=True),
    sa.Column('price_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('name_contains', sa.String(length=255), nullable=True),
    sa.Column('stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_rules_id'), 'purchase_rules', ['id'], unique=False)
    op.create_table('purchase_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_purchase_exceptions_id'), 'purchase_exceptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_exceptions_id'), table_name='purchase_exceptions')
    op.drop_table('purchase_exceptions')
    op.drop_index(op.f('ix_purchase_rules_id'), table_name='purchase_rules')
    op.drop_table('purchase_rules')
    # ### end Alembic commands ###
