"""add_assembly_templates

Revision ID: 30d718db6a83
Revises: 98a98e1a45e6
Create Date: 2026-06-11 11:41:36.247457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d718db6a83'
down_revision: Union[str, Sequence[str], None] = '98a98e1a45e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_assembly_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('child_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_assembly_templates')
    # ### end Alembic commands ###
