"""add sold_price to product_units

Revision ID: 576a9c8d13bf
Revises: 09cf7df8a4fe
Create Date: 2026-06-23 09:23:07.311165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '576a9c8d13bf'
down_revision: Union[str, Sequence[str], None] = '09cf7df8a4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_units', sa.Column('sold_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_purchase_exceptions_id'), table_name='purchase_exceptions')
    op.alter_column('purchase_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_purchase_rules_id'), table_name='purchase_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_purchase_rules_id'), 'purchase_rules', ['id'], unique=False)
    op.alter_column('purchase_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_purchase_exceptions_id'), 'purchase_exceptions', ['id'], unique=False)
    op.drop_column('product_units', 'sold_price')
    # ### end Alembic commands ###
